version: 4.21.0-{branch}-{build}
image: Ubuntu2004
clone_depth: 1
cache:
  - /home/appveyor/.ccache

build_script:
- sh: >-
    git log > /tmp/gitlog.txt

    grep -q '\[ci reset\]' /tmp/gitlog.txt && rm -rf /home/appveyor/.ccache

    sudo apt-get update -qq

    sudo apt-get install -qq wget

    sudo wget https://raw.githubusercontent.com/fluxer/katana-ubuntu/master/katana.list -O /etc/apt/sources.list.d/katana.list

    sudo apt-get update -qq

    sudo apt-get install -qq cmake katie-dev libenchant-dev \
        libmagick++-dev libmpv-dev xorg-dev mesa-common-dev \
        libavahi-common-dev libwebp-dev libudev-dev liblzma-dev \
        libexiv2-dev libbz2-dev libacl1-dev libcdio-dev strigi \
        libdbusmenu-katie media-player-info shared-mime-info \
        media-player-info xdg-utils ccache

    export PATH="/usr/lib/ccache/:$PATH"

    mkdir build

    cd build

    cmake ../ -Wno-dev

    make -j $(nproc || echo 1)
