set(KDE_VERSION_MAJOR "@KDE_VERSION_MAJOR@")
set(KDE_VERSION_MINOR "@KDE_VERSION_MINOR@")
set(KDE_VERSION_RELEASE "@KDE_VERSION_RELEASE@")
set(KDE_VERSION "@KDE_VERSION@")
set(KDE_VERSION_STRING "@KDE_VERSION_STRING@") 

# Compatibility with find_package() query and version requirement
set(PACKAGE_VERSION "${KDE_VERSION}")
set(PACKAGE_VERSION_MAJOR "${KDE_VERSION_MAJOR}")
set(PACKAGE_VERSION_MINOR "${KDE_VERSION_MINOR}")
set(PACKAGE_VERSION_PATCH "${KDE_VERSION_RELEASE}")

# Check whether the requested PACKAGE_FIND_VERSION is compatible
if("${PACKAGE_VERSION}" VERSION_LESS "${PACKAGE_FIND_VERSION}")
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
else()
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
    if ("${PACKAGE_VERSION}" VERSION_EQUAL "${PACKAGE_FIND_VERSION}")
        set(PACKAGE_VERSION_EXACT TRUE)
    endif()
endif()
